apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: netbox
  labels:
    frontend: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      frontend: nginx
  template:
    metadata:
      labels:
        frontend: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.6-alpine
        ports:
        - containerPort: 80
        command: ["nginx"]
        args: ["-c", "/etc/netbox-nginx/nginx.conf","-g", "daemon off;"] 
        volumeMounts:
        - name: netbox-nginx-config
          mountPath: /etc/netbox-nginx
        - name: netbox-static-files 
          mountPath: /opt/netbox/netbox/static
      restartPolicy: Always
      volumes:
      - name: netbox-nginx-config
        configMap:
          name: nginx-conf 
      - name: netbox-static-files
        persistentVolumeClaim:
          claimName: netbox-static-files-pvc-prod
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: netbox
  labels:
    frontend: nginx
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
spec:
  type: LoadBalancer
  loadBalancerIP: 10.67.252.103
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    frontend: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: netbox
data:
  nginx.conf: |
    worker_processes 1;

    error_log /dev/stderr info;

    events {
        worker_connections 1024;
    }

    http {
        include              /etc/nginx/mime.types;
        default_type         application/octet-stream;
        sendfile             on;
        tcp_nopush           on;
        keepalive_timeout    65;
        gzip                 on;
        server_tokens        off;
        client_max_body_size 10M;

        server {
            listen      80;
            access_log  off;
            server_name netbox;            

            location  /static/ {
                alias /opt/netbox/netbox/static/;
            }
 
            location / {
                proxy_pass http://netbox:8001;
                proxy_set_header X-Forwarded-Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Proto $scheme;
                add_header P3P 'CP: "ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
            }
        }
    }